checks:
    php: true

build:
    environment:
        php:
            version: '7.2'
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run

tools:
    external_code_coverage:
        timeout: 600