name: tests

on:
  push:
    branches: [ "3.x" ]
  pull_request:
    branches: [ "3.x" ]

jobs:
  phpunit:
    strategy:
      matrix:
        php_version: [ 8.0, 8.1, 8.2 ]
    runs-on: ubuntu-latest
    name: PHP ${{ matrix.php_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          coverage: xdebug
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction
      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit --coverage-clover coverage.xml
#      - name: Submit coverage report to Coveralls
#        if: ${{ matrix.php_version == 8.0 }}
#        env:
#          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
#        run: ./vendor/bin/php-coveralls --coverage_clover=coverage.xml